name = "fuyu-blog"
main = ".open-next/worker.js"
compatibility_date = "2025-02-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "bun run build:worker"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
